// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/index.tsx";
import * as $3 from "./routes/page/[name].tsx";
import * as $$0 from "./islands/AttrPart.tsx";
import * as $$1 from "./islands/AttrbutesPart.tsx";
import * as $$2 from "./islands/ChangeClassButton.tsx";
import * as $$3 from "./islands/DocPartElems.tsx";
import * as $$4 from "./islands/ListItemElem.tsx";
import * as $$5 from "./islands/Page.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/index.tsx": $2,
    "./routes/page/[name].tsx": $3,
  },
  islands: {
    "./islands/AttrPart.tsx": $$0,
    "./islands/AttrbutesPart.tsx": $$1,
    "./islands/ChangeClassButton.tsx": $$2,
    "./islands/DocPartElems.tsx": $$3,
    "./islands/ListItemElem.tsx": $$4,
    "./islands/Page.tsx": $$5,
  },
  baseUrl: import.meta.url,
};

export default manifest;
